Repository sara-sabr/ITStrategy, pull requests merged in 2019-11, with the labels that each got.

#390 Working open3
  assets/images/oss-linux.png
  assets/images/oss-zsh.png
  presentations/en/2019-11-05-Working-in-the-open.md
Labels: events, open source

#392 Fix print pdf
  _config.yml
  _includes/footer-revealjs.html
  _includes/head-revealjs.html
  _includes/listPresentations.md
Labels: enhancement

#393 Add more references in presentation
  presentations/en/2019-11-05-Working-in-the-open.md
Labels: communications, events, open source

#402 Update Contibuting presentation
  presentations/en/2019-11-12-OSS-Contributing.md
Labels: events, open source

#401 Automation Exercises
  _pages/en/exercises-automation-npm.md
  cspell.json
  presentations/en/2019-11-12-OSS-Publishing.md
  presentations/en/2019-11-12-OSS-Using.md
Labels: events, open source

#406 Change display of blog post list
  _includes/listPosts.md
  _posts/en/2019-09-12-who-we-are.md
  _posts/en/2019-10-15-case-continuous-improvement.md
  _posts/en/2019-11-11-why-we-modified-posts.md
  _posts/fr/2019-09-12-qui-nous-sommes.md
  _posts/fr/2019-11-11-pourquoi-modifier-billets.md
  assets/css/style.css
  assets/images/list-blog-posts-fr.png
  assets/images/list-blog-posts-new-fr.png
  assets/images/list-blog-posts-new.png
  assets/images/list-blog-posts.png
Labels: ad hoc, bug, enhancement

#407 Sections update
  _config.yml
  _pages/en/building-enabling-directorate.md
  _pages/en/capabilities.md
  _pages/en/esdc-it-strategy.md
  _pages/en/it-picture-long-term.md
  _pages/en/it-picture-medium-term.md
  _pages/en/speaking_notes.md
  _pages/en/strategies-actions.md
  _pages/en/strategy-summary.md
  _pages/fr/dgiit-ipc.md
  _pages/fr/retroaction-strategie-it.md
  _pages/fr/sommaire-strategie.md
Labels: enhancement

#423 Continuous series
  _posts/en/2019-10-15-case-continuous-improvement-deeper-dive.md
  _posts/en/2019-10-15-case-continuous-improvement.md
Labels: communications

#424 Simplify modified date logic
  _layouts/post.html
Labels: enhancement

#421 Versioning
  _config.yml
  _includes/versioning.md
  _layouts/default.html
Labels: enhancement

#433 Fix duplicate last modified date
  _layouts/default.html
Labels: ad hoc, bug

#422 Blog working open
  _drafts/en/working-in-the-open-part-1.md
Labels: communications

#442 Publish blog post
  _posts/en/2019-11-19-working-in-the-open-part-1.md
Labels: communications

#441 Update strategies-actions.md (add/regorg)
  _pages/en/strategies-actions.md
Labels: strategies

#436 Translation for blog post Case for continuous improvement
  _posts/en/2019-10-15-case-continuous-improvement.md
  _posts/fr/2019-10-15-arguments-amelioration-continue.md
Labels: communications

#450 Blog travail ouvert
  _posts/en/2019-11-19-working-in-the-open-part-1.md
  _posts/fr/2019-11-19-travailler-ouvertement-partie-1.md
Labels: communications
