Repository sara-sabr/ITStrategy, pull requests merged in 2019-10, with the labels that each got.

#306 Oss presentations
  assets/images/algo-code-soft.png
  assets/images/apache2-gpl-error.png
  assets/images/apache2-gpl-ok.png
  assets/images/due-diligence.png
  assets/images/soft-arch.png
  presentations/en/2019-11-12-OSS-Contributing.md
  presentations/en/2019-11-12-OSS-Publishing.md
  presentations/en/2019-11-12-OSS-Using.md
Labels: open source

#311 Blog case for continuous improvement
  .editorconfig
  .gitignore
  _posts/en/2019-10-15-case-continuous-improvement.md
  assets/images/areaundercurve.PNG
  assets/images/comparecurves1.PNG
  assets/images/drawgraphx2.PNG
  assets/images/fullfunction.PNG
  assets/images/graphx.PNG
  assets/images/graphx2.PNG
  assets/images/graphx2minusxl.PNG
  assets/images/integralareaundercurve.PNG
  cspell.json
  package-lock.json
Labels: communications

#347 Change Categories tag to Sections
  _config.yml
  _includes/listPages.md
  _pages/en/building-enabling-directorate.md
  _pages/en/capabilities.md
  _pages/en/digital-identity-timeline.md
  _pages/en/employee-profiles.md
  _pages/en/how_to_contribute.md
  _pages/en/human-development-life-cycle.md
  _pages/en/iitb-kpi.md
  _pages/en/it-picture-long-term.md
  _pages/en/it-picture-medium-term.md
  _pages/en/mandate.md
  _pages/en/quarterly-delivery.md
  _pages/en/references.md
  _pages/en/service-culture.md
  _pages/en/speaking_notes.md
  _pages/en/strategies-actions.md
  _pages/en/strategy-summary.md
  _pages/en/transition-to-partner.md
  _pages/en/trends.md
  _pages/en/web-services-access.md
  _pages/fr/comment-contribuer.md
  _pages/fr/dgiit-ipc.md
  _pages/fr/mandat.md
  _pages/fr/references.md
  _pages/fr/retroaction-strategie-it.md
  _pages/fr/sommaire-strategie.md
  _pages/fr/tendances.md
Labels: dependencies

#333 Exercises for Using OSS course
  _pages/en/exercises-oss-hugo.md
  _pages/en/exercises-oss-jekyll.md
  cspell.json
Labels: events, open source

#371 Fix instruction links
  presentations/en/2019-11-05-Working-in-the-open.md
  presentations/en/2019-11-12-OSS-Contributing.md
  presentations/en/2019-11-12-OSS-Using.md
Labels: events, open source

#375 Exclude gccode URL from test
  .markdown-link-check.json
Labels: ad hoc, bug

#377 Add subtitles and update notes
  presentations/en/2019-11-05-Working-in-the-open.md
Labels: events, open source
