Repository sara-sabr/ITStrategy, pull requests merged in 2021-01, with the labels that each got.

#1392 Reduce width of blog posts (excl. tables) & adjust font sizes
  _layouts/post.html
  _posts/en/2020-12-10-micro-acquisition-pilot-update1.md
  assets/css/style.css
  cspell.json
Labels: website

#1441 Revert previous change in past PR (blog post width)
  _posts/en/2020-12-10-micro-acquisition-pilot-update1.md
  cspell.json
Labels: website

#1442 Convert from Travis CI to GitHub Actions
  .github/workflows/node.js.yml
  .travis.yml
  link-check.js
Labels: website

#1419 Micro acquisition update blog
  _posts/en/2021-01-05-micro-acquisition-pilot-update1.md
  _posts/fr/2021-01-05-pilote-de-micro-acquisition-mise-a-jour1.md
  cspell.json
Labels: micro-acquisitions

#1443 fix to the blog excerpt
  _posts/fr/2020-12-04-meilleure-technologie-grace-au-micro-approvisionnement-partie-2.md
Labels: micro-acquisitions

#1444 added new blog links to the Micro-Acquisition page
  _pages/en/micro-acquisition-pilot.md
  _pages/fr/pilote-de-micro-acquisition.md
Labels: micro-acquisitions

#1440 Make all images responsive
  assets/css/style.css
Labels: website

#1467 Fix headers
  _posts/en/2019-10-15-case-continuous-improvement.md
Labels: Accessibility
